---
title: "Table1"
author: "Christelle Colin-Leitzinger"
date: "2023-06-30"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE)
```

```{r}
library(tidyverse)
library(gtsummary)
theme_gtsummary_compact()

analysis_data <- read_rds("~/Documents/GitHub/Peres/MilesForMoffittRadiomics/analysis_data_06302023.rds")
```

```{r}
analysis_data %>% 
  select(age_at_diagnosis, year_of_diagnosis,
         race, ethnicity, raceeth, gender,
         bmi, bmi_cat, bmi_cat2,
         tnm_cs_mixed_group_stage, 
         primary_site, grade_differentiation, 
         debulking_status,
         vital_new, has_the_patient_recurred,
         starts_with("preDx"),
         treatment_type,
         contrastenhancementyn
         ) %>% 
  tbl_summary(by= treatment_type,
              type = list(starts_with("PreDx") ~ "categorical")) %>% 
  bold_labels() %>% add_p() %>% bold_p(t= .05) %>% 
  add_overall()
```

