---
title: "Variables to clean"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: darkly #cerulean
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.figure {
   margin-top: 25px;
   <!-- margin-bottom: 100px; -->
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      # fig.width = 7, fig.height = 5, 
                      fig.align='center'#, fig.show='hold'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

```{r library}
library(tidyverse)

library(gtsummary)

```


<br>
<br>
<!-- Leave a space here -->

***

```{r radiomics}
clinical <- read_rds(paste0(here::here(), "/clinical.rds"))
```



```{r}
clinical %>% mutate(dataset = "Patients") %>% distinct(mrn, .keep_all = TRUE) %>% 
  select(everything(), -mrn, -contains("date"), -comment_for_cardiac_comorbidity) %>% 
  tbl_summary(by = dataset, 
              sort = list(everything() ~ "frequency")
              ) %>% 
  bold_labels() %>% as_gt()
```

